<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UserSecretsId>f68b98c8-17fb-4509-b348-77c5d3cc48ef</UserSecretsId>
		<ManagePackageVersionsCentrally>false</ManagePackageVersionsCentrally>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\RiverBooks.Books.Contracts\RiverBooks.Books.Contracts.csproj" />
		<ProjectReference Include="..\RiverBooks.OrderProcessing.Contracts\RiverBooks.OrderProcessing.Contracts.csproj" />
		<ProjectReference Include="..\RiverBooks.ServiceDefaults\RiverBooks.ServiceDefaults.csproj" />
		<ProjectReference Include="..\RiverBooks.SharedKernel\RiverBooks.SharedKernel.csproj" />
		<ProjectReference Include="..\RiverBooks.Users.Contracts\RiverBooks.Users.Contracts.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.23.0" />
		<PackageReference Include="Microsoft.Extensions.Logging.Console" Version="9.0.2" />
		<PackageReference Include="Microsoft.Extensions.Logging.ApplicationInsights"  Version="2.23.0"/>
		<PackageReference Include="Blazor.Bootstrap" Version="3.3.1" />
		<PackageReference Include="Microsoft.AspNetCore.Components.Authorization" Version="9.0.2">
		  <TreatAsUsed>true</TreatAsUsed>
		</PackageReference>
		<PackageReference Update="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.12" />
		<PackageReference Update="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.12" />
		<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="9.0.2" />
		<PackageReference Update="Microsoft.EntityFrameworkCore" Version="8.0.12" />
		<PackageReference Update="Microsoft.EntityFrameworkCore.Relational" Version="8.0.12" />
		<PackageReference Update="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.12" />
		<PackageReference Update="Microsoft.Extensions.Caching.SqlServer" Version="8.0.12" />
	</ItemGroup>

</Project>
