
@RootAddress=http://localhost:8080
@UserEmail=customer@riverbooks.com
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6ImN1c3RvbWVyQHJpdmVyYm9va3MuY29tIiwiSWQiOiIwNjcwMmY4OC1kNTRlLTc0MTAtODAwMC03ZjYyOGU3MDdmYzYiLCJzaWQiOiIwNjcwMmY4OC1mZTVlLTc5NGEtODAwMC0zZDJkNzI3ODBiOWMiLCJhdWQiOiJSaXZlckJvb2tzIiwiaXNzIjoiUml2ZXJCb29rcyIsImV4cCI6MTcyODI1NTE1MSwiaWF0IjoxNzI4MjQ3OTUxLCJuYmYiOjE3MjgyNDc5NTF9.MvZwhO1zzgKeAa3FA_52NYRmmWwySPvuisWNpMhyvk8


# CREATE USER

POST {{RootAddress}}/users
Accept: application/json
Content-Type: application/json

{
  "email":"{{UserEmail}}",
  "password":"Pass@word1"
}

###

# LOGIN
POST {{RootAddress}}/users/login
Accept: application/json
Content-Type: application/json

{
  "email":"{{UserEmail}}",
  "password":"Pass@word1"
}


###

# GET ALL BOOKS

GET {{RootAddress}}/books
Accept: application/json
Authorization: Bearer {{token}}

###

@BookID=06702f8a-83f1-7660-8000-18f4c8601576

# GET BOOK By ID

GET {{RootAddress}}/books/{{BookID}}
Accept: application/json
Authorization: Bearer {{token}}

###

# ADD BOOK

POST {{RootAddress}}/books
Accept: application/json
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "title": "Clean Code",
  "author": "Robert C. Martin",
  "price": 39.99
}

###

# DELETE BOOK

DELETE {{RootAddress}}/books/{{BookID}}
Accept: application/json
Authorization: Bearer {{token}}

###

# UPDATE BOOK'S PRICE

POST {{RootAddress}}/books/{{BookID}}/pricehistory
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

 42.00


###

#ADD BOOK TO CART
POST {{RootAddress}}/cart
Accept: text/plain
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "bookId":"{{BookID}}",
  "quantity":1
}

###

# LIST BOOKS IN CART
GET {{RootAddress}}/cart
Accept: application/json
Authorization: Bearer {{token}}

###

# LIST ALL ORDERS
GET {{RootAddress}}/orders
Accept: application/json
Authorization: Bearer {{token}}

###

# CHECKOUT CART
POST {{RootAddress}}/cart/checkout
Accept: application/json
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "shippingAddressId":"066f85e0-5c39-754d-8000-85a06b8289d9",
  "billingAddressId":"066f85e0-5c39-754d-8000-85a06b8289d9"
}

###

# LIST ADDRESSES

GET {{RootAddress}}/users/addresses
Accept: application/json
Authorization: Bearer {{token}}

###

# ADD ADDRESS TO USER
POST {{RootAddress}}/users/addresses
Accept: application/json
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "street1": "Officestreet",
  "street2": "",
  "city":"City name",
  "state":"State name",
  "postalCode":"00-123",
  "country":"Country name"
}

###

# LIST Processed EMAILS

GET {{RootAddress}}/emails/processed
Accept: application/json
Authorization: Bearer {{token}}

###

# LIST Pending EMAILS

GET {{RootAddress}}/emails/pending
Accept: application/json
Authorization: Bearer {{token}}

###

# TOP SALES - EVENT INGESTION CUSTOM DB

GET {{RootAddress}}/reports/topsales/2024/9
Accept: application/json

###