
@RootAddress=https://localhost:7179


###

# CREATE USER

POST {{RootAddress}}/users
Accept: application/json
Content-Type: application/json

{
  "email":"mirek@test.com",
  "password":"Pass@word1"
}

###

# LOGIN

POST {{RootAddress}}/users/login
Accept: application/json
Content-Type: application/json

{
  "email":"mirek@test.com",
  "password":"Pass@word1"
}

###

@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6Im1pcmVrQHRlc3QuY29tIiwiSWQiOiIwNjY4MmZiYS0xOTg4LTdlYWEtODAwMC0wMzZmY2I2Mjc2MGYiLCJzaWQiOiIwNjY4MmZiYy04YzI5LTcwNTktODAwMC04YjJlZWIwMjY2M2QiLCJleHAiOjE3MTk4NjczNjgsImlhdCI6MTcxOTg2MDE2OCwibmJmIjoxNzE5ODYwMTY4fQ.DazKTVBP1WvpwJxCDSA2f0Ee3udHMjg1gfbMl5vUea8

# GET ALL BOOKS

GET {{RootAddress}}/books
Accept: application/json
Authorization: Bearer {{token}}

###

@BookID=a89f6cd7-4693-457b-9009-02205dbbfe45
GET {{RootAddress}}/books/{{BookID}}
Accept: application/json
Authorization: Bearer {{token}}

###

POST {{RootAddress}}/books
Accept: application/json
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "title": "Clean Coder",
  "author": "Robert C. Martin",
  "price": 19.99
}

###

# Test the location header
GET {{RootAddress}}/books/06682fc2-89a8-730b-8000-9698a79fcb01
Accept: application/json
Authorization: Bearer {{token}}

###

DELETE {{RootAddress}}/books/0667899b-1c4b-72eb-8000-d6b033eb8703
Accept: application/json
Authorization: Bearer {{token}}

###

POST {{RootAddress}}/books/06682fc2-89a8-730b-8000-9698a79fcb01/pricehistory
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

 9.99


### Add item to cart
POST {{RootAddress}}/cart
Accept: text/plain
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "bookId":"06682fbf-0cf2-7353-8000-17e68740046f",
  "quantity":1
}

###

# List items in cart
GET {{RootAddress}}/cart
Accept: application/json
Authorization: Bearer {{token}}

###

# List All Orders
GET {{RootAddress}}/orders
Accept: application/json
Authorization: Bearer {{token}}

###

# Checkout Cart
POST {{RootAddress}}/cart/checkout
Accept: application/json
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "shippingAddressId":"06682fc9-2bce-7205-8000-efc8a47a19eb",
  "billingAddressId":"06682fc9-2bce-7205-8000-efc8a47a19eb"
}

###

# List Addresses

GET {{RootAddress}}/users/addresses
Accept: application/json
Authorization: Bearer {{token}}

###

# Add Address to User
POST {{RootAddress}}/users/addresses
Accept: application/json
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "street1": "Rybitwy 22",
  "street2": "",
  "city":"Gdañsk",
  "state":"Pomorze",
  "postalCode":"12-942",
  "country":"Poland"
}

###

# LIST EMAILS

GET {{RootAddress}}/emails
Accept: application/json
Authorization: Bearer {{token}}

###

# TOP SALES 1 - REACH IN REPORTING

GET {{RootAddress}}/reports/topsales/2024/7
Accept: application/json

###

# TOP SALES 2 - EVENT INGESTION CUSTOM DB

GET {{RootAddress}}/reports/topsales2/2024/7
Accept: application/json

###