
@RootAddress=https://localhost:7179


###

# CREATE USER

POST {{RootAddress}}/users
Accept: application/json
Content-Type: application/json

{
  "email":"mirek@test.com",
  "password":"Pass@word1"
}

###

# LOGIN

POST {{RootAddress}}/users/login
Accept: application/json
Content-Type: application/json

{
  "email":"mirek@test.com",
  "password":"Pass@word1"
}

###

@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6Im1pcmVrQHRlc3QuY29tIiwiSWQiOiIwcjM4YjlveWFhNno2eHZ4cm5ndG5wdGNvIiwic2lkIjoiMDY2ODFiYmEtNWY5ZC03YzlhLTgwMDAtYTE0NTAwZDQxOWY5IiwiZXhwIjoxNzE5Nzg1NDEzLCJpYXQiOjE3MTk3NzgyMTMsIm5iZiI6MTcxOTc3ODIxM30.sHei8EWV1nqThpxWIS223MzCMonSve3DsxCzbtyT51w

# GET ALL BOOKS

GET {{RootAddress}}/books
Accept: application/json
Authorization: Bearer {{token}}

###

@BookID=e4fa19bf-6981-4e50-a542-7c9b26e9ec31
GET {{RootAddress}}/books/{{BookID}}
Accept: application/json
Authorization: Bearer {{token}}

###

POST {{RootAddress}}/books
Accept: application/json
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "title": "Modular Monoliths - Getting Started",
  "author": "Steve Smith",
  "price": 29.99
}

###

# Test the location header
GET {{RootAddress}}/books/066789a1-d0b8-7708-8000-a37d01d02e36
Accept: application/json
Authorization: Bearer {{token}}

###

DELETE {{RootAddress}}/books/0667899b-1c4b-72eb-8000-d6b033eb8703
Accept: application/json
Authorization: Bearer {{token}}

###

POST {{RootAddress}}/books/066789a1-d0b8-7708-8000-a37d01d02e36/pricehistory
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

 39.20


### Add item to cart
POST {{RootAddress}}/cart
Accept: text/plain
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "bookId":"066789a2-c10a-70ac-8000-7e1d5ac78aad",
  "quantity":5
}

###

# List items in cart
GET {{RootAddress}}/cart
Accept: application/json
Authorization: Bearer {{token}}

###

# List All Orders
GET {{RootAddress}}/orders
Accept: application/json
Authorization: Bearer {{token}}

###

# Checkout Cart
POST {{RootAddress}}/cart/checkout
Accept: application/json
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "shippingAddressId":"066789ba-6d0b-7b84-8000-3d0cdf035b5b",
  "billingAddressId":"0667b3e4-2a57-738c-8000-db3fa21a9ad8"
}

###

# List Addresses

GET {{RootAddress}}/users/addresses
Accept: application/json
Authorization: Bearer {{token}}

###

# Add Address to User
POST {{RootAddress}}/users/addresses
Accept: application/json
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "street1": "Rybitwy 22",
  "street2": "",
  "city":"Gdañsk",
  "state":"Pomorze",
  "postalCode":"12-942",
  "country":"Poland"
}

###

# LIST EMAILS

GET {{RootAddress}}/emails
Accept: application/json
Authorization: Bearer {{token}}

###

# TOP SALES 1 - REACH IN REPORTING

GET {{RootAddress}}/topsales?month=6&year=2024
Accept: application/json
Authorization: Bearer {{token}}

###

# TOP SALES 2 - EVENT INGESTION CUSTOM DB

GET {{RootAddress}}/topsales2?month=6&year=2024
Accept: application/json
Authorization: Bearer {{token}}

###