<Project Sdk="Microsoft.NET.Sdk">
	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="MediatR" />
		<PackageReference Include="Serilog.AspNetCore"  />
		<PackageReference Include="Serilog.Extensions.Hosting" />
		<PackageReference Include="Serilog.Settings.Configuration"  />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions"  />
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
		<PackageReference Include="FluentValidation" />
		<PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
		<PackageReference Include="Microsoft.EntityFrameworkCore"  />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Relational" />
		<PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore"  />
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer"  />
		<PackageReference Include="Microsoft.Extensions.Resilience" />
		<PackageReference Include="Microsoft.Extensions.Caching.SqlServer" />
		<PackageReference Include="Microsoft.Extensions.Http.Resilience" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer"  />
	</ItemGroup>
</Project>
