<Project Sdk="Microsoft.NET.Sdk">

	<ItemGroup>
		<InternalsVisibleTo Include="RiverBooks.EventsProcessing.Api" />
		<InternalsVisibleTo Include="RiverBooks.Integration.Tests" />
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.11" />
	  <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.11" />
	  <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="8.0.11" />
	  <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="8.0.2" />
	  <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.2" />
	  <PackageReference Include="Serilog.AspNetCore" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\RiverBooks.EventsProcessing.Contracts\RiverBooks.EventsProcessing.Contracts.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Update="Serilog.AspNetCore" Version="8.0.3" />
	</ItemGroup>

</Project>
