<Project Sdk="Microsoft.NET.Sdk">

	<Sdk Name="Aspire.AppHost.Sdk" Version="9.0.0" />

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<IsAspireHost>true</IsAspireHost>
		<UserSecretsId>cd169d42-c94f-44a6-a004-00006e394347</UserSecretsId>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Aspire.Hosting.AppHost" />
		<PackageReference Include="Aspire.Hosting.SqlServer" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\RiverBooks.Presentation\RiverBooks.Presentation.csproj" />
		<ProjectReference Include="..\RiverBooks.Web\RiverBooks.Web.csproj" />
	</ItemGroup>

</Project>
