<Project>
	<PropertyGroup>
		<LangVersion>latest</LangVersion>
		<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Serilog.AspNetCore" Version="8.0.3" />
		<PackageReference Include="MediatR" Version="12.3.0" />
		<PackageReference Include="Serilog.Extensions.Hosting" Version="8.0.0" />
		<PackageReference Include="Serilog.Settings.Configuration" Version="8.0.4" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="8.0.2" />
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.2" />
		<PackageReference Include="FluentValidation" Version="11.11.0" />
		<PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="11.11.0" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.11" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.11" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="8.0.11" />
		<PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.11" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.11" />
		<PackageReference Include="Microsoft.Extensions.Resilience" Version="8.10.0" />
		<PackageReference Include="Microsoft.Extensions.Caching.SqlServer" Version="8.0.11" />
	</ItemGroup>
</Project>