<Project>
	<PropertyGroup>
		<LangVersion>latest</LangVersion>
		<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Serilog.AspNetCore" Version="[8.0.3, 9.0.0)" />
		<PackageReference Include="MediatR" Version="12.4.1" />
		<PackageReference Include="Serilog.Extensions.Hosting" Version="[8.0.0, 9.0.0)" />
		<PackageReference Include="Serilog.Settings.Configuration" Version="[8.0.4, 9.0.0)" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="[8.0.2, 9.0.0)" />
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="[8.0.2, 9.0.0)" />
		<PackageReference Include="FluentValidation" Version="11.11.0" />
		<PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="11.11.0" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="[8.0.11, 9.0.0)" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="[8.0.11, 9.0.0)" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="[8.0.11, 9.0.0)" />
		<PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="[8.0.11, 9.0.0)" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="[8.0.11, 9.0.0)" />
		<PackageReference Include="Microsoft.Extensions.Resilience" Version="9.0.0" />
		<PackageReference Include="Microsoft.Extensions.Caching.SqlServer" Version="[8.0.11, 9.0.0)" />
	</ItemGroup>
</Project>