<Project Sdk="Microsoft.NET.Sdk">

	<ItemGroup>
		<InternalsVisibleTo Include="RiverBooks.EmailSending.Api" />
		<InternalsVisibleTo Include="RiverBooks.Integration.Tests" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\RiverBooks.EmailSending.Contracts\RiverBooks.EmailSending.Contracts.csproj" />
		<ProjectReference Include="..\RiverBooks.SharedKernel\RiverBooks.SharedKernel.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Infrastructure\Migrations\" />
	</ItemGroup>

</Project>
